### ISSUE TITLE
Link metadata ID to SRA sample name

### ISSUE THREAD

**Issue by MSMortensen** [mmpust/airway-metagenome-infants#1]
Hi,

First of all this is a very impressive project.

I'm interested in using your data to test some classification tools and want to be able to differentiate between samples from healthy and non-healthy individuals.

Can you help me link the metadata in this repository to the files available in SRA (PRJEB38221).

Kind regards,
Martin Mortensen

**Comment by mmpust** [comment]
Dear Dr. Mortensen, 

Thank you for your patience. I have now added an extra file containing the SRA accession numbers and corresponding metadata IDs. I am very much looking forward to hearing (or reading) about your classification approaches. Please note that the FASTQ files of this project have been altered to remove human DNA reads. It will therefore not be possible to use absolute abundance based on human read normalizations, which would be the best foundation for any clustering approach. If you would like to cluster based on absolute microbial abundances, you may work with the provided final counts after alignment and normalisation to human read counts.

Kind regards,
Marie Pust

**Comment by MSMortensen** [comment]
Dear Marie Pust,

Thank you so much, this was exactly what I needed.

Kind regards,
Martin

**Comment by mmpust** [comment]
Dear Martin,

Great! Please let me know if you need further clarifications or guidance in regards to the dataset.

Kind regards,
Marie
